# configure Apache

- name: edit /etc/apache2/ports.conf
  copy: content="Listen 443" dest=/etc/apache2/ports.conf
- name: copy /etc/ssl/certs/backend.server.dc.crt
  copy:
    src: backend.server.dc.crt
    dest: /etc/ssl/certs/backend.server.dc.crt
- name: copy /etc/ssl/private/backend.server.dc.key
  copy:
    src: backend.server.dc.key
    dest: /etc/ssl/private/backend.server.dc.key
    mode: 0600
- name: create site 001-reverse-proxy
  template:
    src: 001-reverse-proxy.conf.j2
    dest: /etc/apache2/sites-available/001-reverse-proxy.conf
- name: enable site 001-reverse-proxy
  block:
  - name: enable site 001-reverse-proxy
    shell: a2ensite 001-reverse-proxy
  - name: systemctl reload apache2.service
    shell: systemctl reload apache2.service
