- name: configure /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: "127.0.1.1 {{ansible_hostname}} {{ansible_hostname}}"
    line: "{{ansible_default_ipv4.address}} \
      {{ansible_hostname}}.{{mail_domain}} {{ansible_hostname}}"
    backrefs: yes
