- import_tasks: hosts.yml
  when: ansible_system_vendor == 'Hetzner' 
- name: install and configure Exit4
  block:
  - name: install exim4-config 
    apt:
      name: exim4-config
      state: latest
