- name: iptables -A INPUT -p tcp --dport 9100 -j REJECT 
  iptables: 
    chain: INPUT 
    protocol: tcp
    destination_port: 9100
    jump: REJECT
- name: install prometheus-node-exporter
  apt:
    name: prometheus-node-exporter
- name: copy prometheus-node-exporter.service
  shell: cp /lib/systemd/system/prometheus-node-exporter.service \
    /etc/systemd/system
- name: edit prometheus-node-exporter.service
  replace:
    path: /etc/systemd/system/prometheus-node-exporter.service
    regexp: '^(ExecStart=/usr/bin/prometheus-node-exporter \$ARGS)$'
    replace: '\1 --web.listen-address=localhost:9101'
- name: systemctl daemon-reload
  shell: systemctl daemon-reload
- name: iptables -D INPUT -p tcp --dport 9100 -j REJECT 
  iptables: 
    chain: INPUT
    protocol: tcp
    destination_port: 9100
    jump: REJECT
    state: absent
- name: restart prometheus-node-exporter
  service: 
    name: prometheus-node-exporter 
    state: restarted 

- name: "mkdir {{common_bin}}"
  file:
    path: "{{common_bin}}"
    state: directory
- name: copy create_textfile.sh
  template:
    src: create_textfile.sh.j2
    dest: "{{common_bin}}/create_textfile.sh"
    mode: u+x
- name: "mkdir {{common_text_exporter}}"
  file:
    path: "{{common_text_exporter}}"
    state: directory
