- name: "mkdir {{common_bin}}"
  file:
    path: "{{common_bin}}"
    state: directory
- name: "copy {{common_bin}}/create_textfile.sh"
  template:
    src: create_textfile.sh.j2
    dest: "{{common_bin}}/create_textfile.sh"
    mode: u+x
- name: "mkdir {{common_text_collectors}}"
  file:
    path: "{{common_text_collectors}}"
    state: directory
- name: install text collector apt.sh
  block:
  - name: "copy {{common_text_collectors}}/apt.sh" 
    copy:
      src: apt.sh
      dest: "{{common_text_collectors}}/apt.sh"
      mode: u+x
  - name: crontab apt
    cron:
      name: apt 
      minute: "*/5"
      user: root
      job: >
        {{common_text_collectors}}/apt.sh |
        {{common_bin}}/create_textfile.sh apt
